ct-js/docs.ctjs.rocks

docs/skeletal-animation.md
Simple way to check animation.isCompleted, as the dragonbones API for animation.isCompleted doesn't seem to work correctly.
=> How to stop animation after it's played once

docs/.vuepress/config.js, docs/ct.timer.md
To be merged with [ct-js#179](https://github.com/ct-js/ct-js/pull/179).
Documentation for [ct-js#179](https://github.com/ct-js/ct-js/pull/179).
=> ct.timer docs

docs/bitmap-fonts.md
=> Fixed fonts property

docs/tut-making-platformer.md
Added a little notice about background tearing.
See https://5f42af7bfb1e090009149753--clever-shaw-0cdd72.netlify.app/tut-making-platformer.html#adding-a-room
=> :pencil: Added a little tip about backgrounds splitting into squares

docs/tut-making-platformer.md
This part was missing from the tutorial
=> :bug: Add missing part to platformer tutorial

docs/localstorage.md
=> things -> strings

docs/dragging-copies.md
Removed merge conflict from example code
=> 📝 Update dragging-copies.md

docs/jsintro_pt3.md
Hai There! 👋
@CosmoMyzrailGorynych, I have found a few minor spelling and grammatical errors in the "Intro to JS Part 3" Documentation!
I have fixed them and have opened this pull request with the changes!
Thanks for reviewing this pull request!
Good day!
=> 📝 JS Intro Pt 3 Docs: Fix Grammar & Spelling

docs/Room.md, docs/content-subsystem.md, docs/ct-concepts.md, docs/ct.inputs.md, docs/ct.styles.md
Hi there! I was looking through the ct.js documentation when I noticed that there were a few, minor, grammatical errors on some pages. Since I already found them, I thought I might as well save you the trouble of fixing them by fixing them myself! 😄
@CosmoMyzrailGorynych thank you and have a great day/afternoon/evening/night!
=> 📝 Minor Documentation Improvements

docs/tut-making-jettycat.md
=> tut JettyCat changes

docs/tut-making-platformer.md
insert a space needed in js code highlighting snippet
=> insert a space in text

docs/tut-making-shooter.md
set angle value for correct moving of enemies and asteroids
=> set angle values

docs/it/README.md, docs/it/ct-concepts.md, docs/it/jsintro_pt1.md, docs/it/jsintro_pt2.md, docs/it/jsintro_pt3.md, docs/it/tut-making-jettycat.md, docs/it/tut-making-platformer.md, docs/it/tut-making-shooter.md, docs/it/tut-polishing-jettycat.md
translation of the four tutorial in italian
=> tutorial translation in italian

docs/jsintro_pt1.md
On Destroy -> Destruction
On Step -> Frame start
=> jsintro_pt1 changes

docs/it/tut-making-jettycat.md, docs/it/tut-making-platformer.md, docs/it/tut-making-shooter.md, docs/it/tut-polishing-jettycat.md
Added translation of code comments.
Added a line at the end with link to etch.io deployment guide.
=> :zap: It translation code comments

docs/skeletal-animation.md
=> :zap: old terms in skeletal-animation.md

docs/.vuepress/config.js, docs/it/README.md, docs/it/actions.md, docs/it/bitmap-fonts.md, docs/it/building-your-game.md, docs/it/content-subsystem.md, docs/it/deployment-itch-io.md, docs/it/room-editor.md, docs/it/skeletal-animation.md
added working-with-editor translated files and menu config.js updates
=> :pencil: italian translation working-with-editor

docs/tut-making-platformer.md
=> multiply horizontal x-change with delta when robot travels on platform

docs/ct.md
=> Change single spelling error

docs/ct.emitters.md
=>  📝Fix typo in example code

docs/README.md, docs/pt_BR/README.md, docs/ru/README.md
- Фикс ссылок, которые ведут в никуда на русскоязычной версии сайта.
- Фикс ссылки на форум на всех языках
=> :bug: ru/README.md fix links

docs/backgrounds.md, docs/content-subsystem.md
in content-subsystem.md and backgrounds.md there were some outdated links that Stuck Up Creations posted on the ctjs discord so i think i fixed them i guess
=> Fix incorrect links

docs/modding-ctjs/mod-structure.md
Fixed Warning typo for .md template
=> Fix typo in mod-structure.md
